app/views/layouts/application.html.erb

コンフリクトを起こす

---

app/views/layouts/application.html.erb

コンフリクトを起こしてみよう

---

app/javascript/packs/application.js

bootstrap入れたときにjqueryも入ってるんだった。

[add]js, jquery

---

app/models/address.rb
app/models/admin.rb
app/models/item.rb
db/migrate/20231214060138_create_addresses.rb
db/migrate/20231214062031_create_items.rb
db/migrate/20231214062727_create_admins.rb
test/fixtures/addresses.yml
test/fixtures/admins.yml
test/fixtures/items.yml
test/models/address_test.rb
test/models/admin_test.rb
test/models/item_test.rb

マイグレーションファイル作成
- adresses
- admins
- items

Add migrate_address_item_admin

---

app/models/cart_item.rb
app/models/genre.rb
app/models/order_detail.rb
db/migrate/20231214065230_create_genres.rb
db/migrate/20231214065731_create_cart_items.rb
db/migrate/20231214070216_create_order_details.rb
db/schema.rb
test/fixtures/cart_items.yml
test/fixtures/genres.yml
test/fixtures/order_details.yml
test/models/cart_item_test.rb
test/models/genre_test.rb
test/models/order_detail_test.rb

genre、cart_item、order_detailモデルの追加＆マイグレーションファイルの作成

[Add]genre,cart_item,order_detailモデルの追加

---

app/controllers/admin/sessions_controller.rb
app/views/admin/sessions/new.html.erb
app/views/layouts/_header.html.erb
db/migrate/20231215085616_add_rememberable_to_admins.rb
db/schema.rb
db/seeds.rb

パスワード、メールアドレスはログイン画面に書いてあります。
ヘッダーの「管理者」を押すとログイン画面に行きます。もう一度押すとログアウトし、ログイン画面に遷移します。

[add]adminのログイン・ログアウト機能

---

app/controllers/admin/customers_controller.rb
app/views/admin/customers/index.html.erb
app/views/admin/customers/show.html.erb
db/seeds.rb

Sato[add]customer(index, show)

---

app/controllers/admin/customers_controller.rb
app/views/admin/customers/edit.html.erb
app/views/admin/customers/show.html.erb

[add]edit画面

---

app/controllers/admin/customers_controller.rb
app/controllers/public/customers_controller.rb
app/controllers/public/items_controller.rb
app/models/customer.rb
app/views/public/customers/show.html.erb
app/views/public/homes/top.html.erb

佐藤さんの渾身のseedファイルで表示確認済み
＋params見た目でちょっと余計なことしました、おそらくコンフリクト出ます

[Add]マイページ/customer実装

---

app/views/public/sessions/new.html.erb

[Add]顧客のログイン画面作成

---

app/controllers/admin/items_controller.rb
app/views/admin/items/new.html.erb
app/views/public/customers/show.html.erb
app/views/public/customers/unsubscribe.html.erb
app/views/public/homes/about.html.erb
app/views/public/homes/top.html.erb

[Add]admin商品新規追加ページ/つくりかけ

---

app/controllers/admin/genres_controller.rb
app/controllers/admin/items_controller.rb
app/models/item.rb
app/views/admin/items/new.html.erb

[Add＆Fix]itemコントローラー、admin新規商品追加にジャンル選択プルダウン

---

app/controllers/public/cart_items_controller.rb
app/models/cart_item.rb
app/models/item.rb
app/views/admin/genres/index.html.erb
app/views/layouts/_header.html.erb
app/views/public/cart_items/index.html.erb
db/migrate/20231217063840_add_reset_password_token_to_customers.rb
db/migrate/20231217064237_add_reset_password_fields_to_customers.rb
db/schema.rb
db/seeds.rb

emailの編集を可能にするためにcustomerテーブルに色々追加。
seedでカート内に1つ商品追加。
たぶん税込み価格をめぐってコンフリクト。

[add]カート一覧。エラー解決。ヘッダーもいじった。

---

app/views/admin/items/edit.html.erb

[add]admin商品編集ページ

---

app/controllers/public/orders_controller.rb
app/models/order.rb
app/views/public/orders/index.html.erb
app/views/public/orders/show.html.erb

[add]order_index,show(仮)

---

app/assets/stylesheets/admin/searches.scss
app/assets/stylesheets/public/searches.scss
app/controllers/admin/searches_controller.rb
app/controllers/application_controller.rb
app/controllers/public/searches_controller.rb
app/helpers/admin/searches_helper.rb
app/helpers/public/searches_helper.rb
app/views/admin/searches/search.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/_search.html.erb
app/views/public/searches/search.html.erb
config/routes.rb
test/controllers/admin/searches_controller_test.rb
test/controllers/public/searches_controller_test.rb

- customerの商品検索はおそらくOKです
- adminのユーザー検索は怪しいです
- ユーザーを管理者側で検索するとなったとき、どの項目で検索するんだろうという疑問が（名前で検索するか？）

検索機能（検索ページ）追加

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/orders_controller.rb
app/models/order.rb
app/models/order_detail.rb
app/views/admin/orders/show.html.erb
app/views/public/items/show.html.erb
app/views/public/orders/confirm.html.erb
config/application.rb
config/locales/ja.yml

enum無しで表示できるように組んでいたところ申し訳ありませんが、
せっかくなのでenumで表示できるように諸々を追加しました
商品のカート追加もこれで可能になったと思います

[Add]余計な手出し/enumで注文ステータスと製作ステータスを表示できるように日本語化ファイルなど追加

---

app/javascript/script.js
app/javascript/stylesheets/application.scss
app/views/layouts/_header.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/customers/show.html.erb
app/views/public/items/index.html.erb

bootstrapのボタンの色はポップすぎると思ったので落ち着いた色合いに変更。
気に入らなければ戻すか変更して大丈夫です。
カートのテーブルも色変更。

[update]btn-primary/successの色を変更。トグルボタンにjs追加。

---

app/assets/config/manifest.js
app/assets/javascripts/slideshow.js.erb
app/controllers/public/homes_controller.rb
app/views/public/homes/top.html.erb
app/views/public/items/_index.html.erb
app/views/public/items/index.html.erb
config/initializers/assets.rb

TOPページレイアウト修正とJsでのスライドショー実装

---

app/controllers/public/customers_controller.rb
app/views/public/customers/unsubscribe.html.erb

すっかり忘れていたので追加しました
今のところフラッシュメッセージは未実装

[Add]退会がきちんと動作するように

---

app/controllers/public/registrations_controller.rb
app/views/public/registrations/new.html.erb

[fix]会員新規登録ができなかったエラー解消

---

config/locales/devise.ja.yml
config/locales/ja.yml

- devise.ja.ymlの方が上位のようなので、そちらで日本語化を設定
- ファイル自体は真似してきたので、表示されるカラムは適宜修正要
- attributeの重複は、デフォルトが見出しに1つ付くようなのでゴリ押しで解決

[Fix]エラーメッセージ表示/日本語化解決

---

app/controllers/application_controller.rb
app/views/admin/searches/search.html.erb
app/views/layouts/_search.html.erb

[Fix]admin側 カスタマー検索修正（実装）

---

app/controllers/public/registrations_controller.rb
app/views/admin/homes/top.html.erb
app/views/admin/items/_table.html.erb

[fix]新規会員登録後の遷移先をマイページに修正

---

app/controllers/admin/orders_controller.rb
app/views/admin/genres/index.html.erb
app/views/public/homes/about.html.erb

- 製作ステータスに1つでも製作中があると→注文ステータスが製作中に変わる
- 製作ステータスを全て製作完了にすると→注文ステータスが発送準備中に変わる
を追加
アバウトにトップと同様のスライドショーを追加

[Fix]admin 製作ステータスと注文ステータスの連動
